#!/bin/bash

# BitTorrent Client - Practical Examples
# Shows how to use the client with DIFFERENT torrents

echo "=================================="
echo "BitTorrent Client - Examples"
echo "=================================="
echo ""

# Build the client if not already built
if [ ! -f "torrent-client" ]; then
    echo "Building client..."
    go build -o torrent-client
    echo "✓ Build complete"
    echo ""
fi

# Example 1: Big Buck Bunny (provided)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 1: Video File (Provided Test Torrent)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "  ./torrent-client big-buck-bunny.torrent"
echo ""
echo "What it does:"
echo "  - Downloads a 364 MB video file"
echo "  - Validates each piece with SHA-1"
echo "  - Saves to: \$HOME/big_buck_bunny.mp4"
echo ""
echo "Usage:"
echo "  ./torrent-client big-buck-bunny.torrent"
echo ""

# Example 2: Linux Distribution
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 2: Linux Distribution ISO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Where to find:"
echo "  - Ubuntu: https://ubuntu.com/download/desktop"
echo "  - Arch: https://archlinux.org/download/"
echo "  - Fedora: https://fedoraproject.org/en/get/workstation/"
echo ""
echo "Command:"
echo "  ./torrent-client ubuntu-22.04-desktop-amd64.iso.torrent"
echo ""
echo "What it does:"
echo "  - Downloads ~4 GB ISO image"
echo "  - Validates integrity"
echo "  - Ready to burn to USB/DVD"
echo ""

# Example 3: Software Package
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 3: Go Programming Language"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Where to find:"
echo "  - Look for .torrent files on archive sites"
echo "  - Or download source: https://go.dev/dl/"
echo ""
echo "Command:"
echo "  ./torrent-client go1.23.0.linux-amd64.tar.gz.torrent"
echo ""
echo "What it does:"
echo "  - Downloads ~300 MB compressed archive"
echo "  - Validates checksum"
echo "  - Extract with: tar -xzf go1.23.0.linux-amd64.tar.gz"
echo ""

# Example 4: Multi-file Archive
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 4: Project Source Code"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "  ./torrent-client project-source.tar.gz.torrent"
echo ""
echo "What it downloads:"
echo "  project/
echo "  ├── src/
echo "  │   ├── main.go"
echo "  │   ├── utils.go"
echo "  │   └── config.go"
echo "  ├── tests/"
echo "  ├── README.md"
echo "  ├── LICENSE"
echo "  └── go.mod"
echo ""
echo "What it does:"
echo "  - Downloads all files together"
echo "  - Reconstructs folder structure"
echo "  - Ready to compile/use"
echo ""

# Example 5: Magnet Link
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 5: Using Magnet Links"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Example from magnets.txt:"
MAGNET=$(head -1 magnets.txt)
echo "  $MAGNET"
echo ""
echo "Command:"
echo "  ./torrent-client \"\$(cat magnets.txt | head -1)\""
echo ""
echo "Or direct:"
echo "  ./torrent-client \"magnet:?xt=urn:btih:...&tr=...&dn=...\""
echo ""
echo "What it does:"
echo "  - No .torrent file needed"
echo "  - Directly contact trackers"
echo "  - Download starts immediately"
echo ""

# Example 6: Batch Download
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 6: Download Multiple Torrents"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "  for torrent in *.torrent; do"
echo "    echo \"Downloading: \$torrent\""
echo "    ./torrent-client \"\$torrent\""
echo "  done"
echo ""
echo "What it does:"
echo "  - Downloads all .torrent files in directory"
echo "  - One after another"
echo "  - Shows progress for each"
echo ""

# Example 7: Using Magnet from File
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 7: Save & Download from Magnet File"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Setup:"
echo "  echo 'magnet:?xt=urn:btih:...' > my-magnet.txt"
echo ""
echo "Command:"
echo "  ./torrent-client \"\$(cat my-magnet.txt)\""
echo ""
echo "What it does:"
echo "  - Reads magnet from file"
echo "  - Starts download immediately"
echo ""

# Example 8: Bench Download Speed
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 8: Measure Download Speed"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "  time ./torrent-client file.torrent"
echo ""
echo "What it shows:"
echo "  real	5m30.234s"
echo "  user	0m10.123s"
echo "  sys	0m5.456s"
echo ""
echo "Calculation:"
echo "  Speed = File Size / Real Time"
echo "  Example: 500MB / 5.5 min = 91 MB/min"
echo ""

# Example 9: Redirect Output to Log
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 9: Save Download Log"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "  ./torrent-client file.torrent | tee download.log"
echo ""
echo "What it does:"
echo "  - Shows output in terminal"
echo "  - Saves everything to download.log"
echo "  - Can review logs later"
echo ""

# Example 10: Background Download
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 10: Background Download"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "  nohup ./torrent-client file.torrent > download.log 2>&1 &"
echo ""
echo "What it does:"
echo "  - Downloads in background"
echo "  - Process continues if terminal closes"
echo ""
echo "Check progress:"
echo "  tail -f download.log"
echo ""

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "KEY POINTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Works with ANY .torrent file"
echo "✅ Works with ANY magnet link"
echo "✅ Downloads ANY file type"
echo "✅ Handles single & multi-file torrents"
echo "✅ No configuration needed"
echo "✅ Automatic torrent/magnet detection"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
